Port: 8080
LogLevel: debug
Services:
  Cars: http://cars-service:8070
  Rental: http://rental-service:8060
  Payment: http://payment-service:8050
Kafka:
  Brokers:
    - kafka:29092
  CarsServiceRetryTopic: cars_service.retry
  PaymentServiceRetryTopic: payment_service.retry
